export const FETCH_ROUNDS = 'FETCH_ROUNDS';
export const FETCH_ROUND = 'FETCH_ROUND';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAM = 'FETCH_TEAM';

export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYER = 'FETCH_PLAYER';

export const FETCH_POSITIONS = 'FETCH_POSITIONS';

export const SIGN_UP = 'SIGN_UP';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const PROFILE = 'PROFILE';
export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';

export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const JOIN_LEAGUE = 'JOIN_LEAGUE';
export const EDIT_LEAGUE = 'EDIT_LEAGUE';
export const UPDATE_LEAGUE = 'UPDATE_LEAGUE';
export const FETCH_LEAGUE = 'FETCH_LEAGUE';
export const GENERATE_PICK_NUMBERS = 'GENERATE_PICK_NUMBERS';
export const UPDATE_DRAFT_PICK_ORDER = 'UPDATE_DRAFT_PICK_ORDER';
export const CREATE_DRAFT = 'CREATE_DRAFT';
export const FETCH_UNPICKED_PLAYERS = 'FETCH_UNPICKED_PLAYERS';

export const FETCH_DRAFT_PICKS = 'FETCH_DRAFT_PICKS';
export const UPDATE_DRAFT_PICK = 'UPDATE_DRAFT_PICK';

export const FETCH_FPL_TEAMS = 'FETCH_FPL_TEAMS';
export const FETCH_FPL_TEAM = 'FETCH_FPL_TEAM';
export const UPDATE_FPL_TEAM = 'UPDATE_FPL_TEAM';

export const FETCH_FPL_TEAM_LIST = 'FETCH_FPL_TEAM_LIST';
export const UPDATE_FPL_TEAM_LIST_ORDER = 'UPDATE_FPL_TEAM_LIST_ORDER';

export const FETCH_LIST_POSITION = 'FETCH_LIST_POSITION';

export const CREATE_WAIVER_PICK = 'CREATE_WAIVER_PICK';
export const FETCH_CURRENT_WAIVER_PICKS = 'FETCH_CURRENT_WAIVER_PICKS';
export const FETCH_WAIVER_PICKS = 'FETCH_WAIVER_PICKS';
export const UPDATE_WAIVER_PICK_ORDER = ' UPDATE_WAIVER_PICK_ORDER';
export const DELETE_WAIVER_PICK = 'DELETE_WAIVER_PICK';

export const SHOW_ROUND_ERRORS = 'SHOW_ROUND_ERRORS';
export const SHOW_USER_ERRORS = 'SHOW_USER_ERRORS';
export const SHOW_TEAM_ERRORS = 'SHOW_TEAM_ERRORS';
export const SHOW_PLAYER_ERRORS = 'SHOW_TEAM_ERRORS';
export const SHOW_LEAGUE_ERRORS = 'SHOW_LEAGUE_ERRORS';
export const SHOW_FPL_TEAM_ERRORS = 'SHOW_FPL_TEAM_ERRORS';
export const SHOW_FPL_TEAM_LIST_ERRORS = 'SHOW_FPL_TEAM_LIST_ERRORS';
export const SHOW_LIST_POSITION_ERRORS = 'SHOW_LIST_POSITION_ERRORS';
export const SHOW_WAIVER_PICK_ERRORS = 'SHOW_WAIVER_PICK_ERRORS';
export const SHOW_DRAFT_PICK_ERRORS = 'SHOW_DRAFT_PICK_ERRORS';

// export const FETCH_CURRENT_ROUND = 'FETCH_CURRENT_ROUND';
//
// export const FETCH_FPL_TEAM_LISTS = 'FETCH_FPL_TEAM_LISTS';

// export const UPDATE_FPL_TEAM_LIST = 'UPDATE_FPL_TEAM_LIST';
//
// export const TRADE_PLAYERS = 'TRADE_PLAYERS';
//
// export const FETCH_MINI_DRAFT_PICKS = 'FETCH_MINI_DRAFT_PICKS';
// export const CREATE_MINI_DRAFT_PICK = 'CREATE_MINI_DRAFT_PICK';
// export const PASS_MINI_DRAFT_PICK = 'PASS_MINI_DRAFT_PICK';
//
// export const INTER_TEAM_TRADE_GROUPS = 'INTER_TEAM_TRADE_GROUPS';
// export const CREATE_INTER_TEAM_TRADE_GROUP = 'CREATE_INTER_TEAM_TRADE_GROUP';
// export const ADD_TO_INTER_TEAM_TRADE_GROUP = 'ADD_TO_INTER_TEAM_TRADE_GROUP';
// export const SUBMIT_INTER_TEAM_TRADE_GROUP = 'SUBMIT_INTER_TEAM_TRADE_GROUP';
// export const DELETE_INTER_TEAM_TRADE_GROUP = 'DELETE_INTER_TEAM_TRADE_GROUP';
// export const REMOVE_INTER_TEAM_TRADE = 'REMOVE_INTER_TEAM_TRADE';
// export const APPROVE_INTER_TEAM_TRADE_GROUP = 'APPROVE_INTER_TEAM_TRADE_GROUP';
// export const DECLINE_INTER_TEAM_TRADE_GROUP = 'DECLINE_INTER_TEAM_TRADE_GROUP';
